config/routes.rb
Rails.application.routes.draw do
  resources :faqs
  root to: 'pages#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/faq.rb
class Faq < ApplicationRecord
  include PgSearch
  pg_search_scope :search, against: %i[question answer], using: { tsearch: { prefix: true } }

  validates :answer, presence: true
  validates :question, presence: true

  def formatted_answer
    answer.gsub(/\<(http[A-z0-9\:\/\.]*?)\>/, '\1')
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/faqs_controller.rb
class FaqsController < ApplicationController
  def index
    if params[:query]
      @faqs = Faq.search(params[:query])
    else
      @faqs = Faq.all
    end
  end

  def edit
    @faq = Faq.find(params[:id])
  end

  def update
    @faq = Faq.find(params[:id])
    if @faq.update(faq_params)
      flash[:success] = 'Successfully edited'
    else
      flash[:error] = 'Could not edit'
    end
    redirect_to faqs_path
  end

  def destroy
    @faq = Faq.find(params[:id])
    @faq.destroy
    flash[:success] = 'Successfully deleted'
    redirect_to faqs_path
  end

  private

  def faq_params
    params.require(:faq).permit(:question, :answer)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
    if params[:query]
      @faqs = Faq.search(params[:query])
    else
      @faqs = Faq.all
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/faqs/edit.html.erb
<section class='section'>
  <div class='box'>
    <%= form_for @faq do |form| %>
      <div class='field'>
        <%= form.label :question, class: 'label' %>
        <%= form.text_field :question, class: 'input' %>
      </div>

      <div class='field'>
        <%= form.label :answer, class: 'label' %>
        <%= form.text_field :answer, class: 'input' %>
      </div>

      <%= form.submit 'Save', class: 'button is-primary' %>
    <% end %>
  </div>
</section>

app/views/faqs/index.html.erb
<section class='section'>
  <%- @faqs.each do |faq| %>
    <div class='box'>
      <strong><%= faq.question %></strong>
      <%= faq.answer %>
      <div class='actions'>
        <%= link_to 'Edit', edit_faq_path(faq) %>
        <%= link_to 'Delete', faq_path(faq), method: :delete %>
      </div>
    </div>
  <% end %>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SlackFaqBot</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render partial: 'shared/flash' %>
    <%= render partial: 'shared/search' %>
    <%= yield %>
  </body>
</html>

app/views/pages/index.html.erb
<h1>FAQs</h1>

app/views/shared/_flash.html.erb
<% flash.each do |key, value| %>
  <div class="notification is-primary">
    <%= value %>
  </div>
<% end %>

app/views/shared/_search.html.erb
<%= form_for :search, url: faqs_path, method: :get, html: { class: 'search-form' } do |form| %>
  <div class='field has-addons'>
    <div class='control is-expanded is-fullwidth'>
      <%= text_field_tag :query, nil, { class: 'input', placeholder: 'Search' } %>
    </div>
    <div class='control'>
      <%= form.submit 'Search', class: 'button is-info' %>
    </div>
  </div>
<% end %>